
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getTimerState() : Promise<Result<TimerState, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_timer_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async beginInterval() : Promise<Result<number, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("begin_interval") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async endInterval() : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("end_interval") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async endIntervalAt(endMs: number) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("end_interval_at", { endMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getIntervals(fromMs: number, toMs: number) : Promise<Result<Interval[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_intervals", { fromMs, toMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRangeTotal(fromMs: number, toMs: number) : Promise<Result<RangeTotal, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_range_total", { fromMs, toMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCurrentGoal() : Promise<Result<DailyGoal | null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_goal") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setDailyGoal(goalMs: number) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_daily_goal", { goalMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateInterval(id: number, startMs: number, endMs: number | null) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_interval", { id, startMs, endMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteInterval(id: number) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_interval", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showSystemPopup(title: string, message: string) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_system_popup", { title, message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDailyTotals(fromDay: string, toDay: string) : Promise<Result<DailyTotal[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_daily_totals", { fromDay, toDay }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDailyGoalsForRange(fromDay: string, toDay: string) : Promise<Result<DailyGoal[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_daily_goals_for_range", { fromDay, toDay }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getStreak(asOfDay: string) : Promise<Result<number, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_streak", { asOfDay }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
idleDetected: IdleDetected,
intervalChanged: IntervalChanged,
popupShow: PopupShow
}>({
idleDetected: "idle-detected",
intervalChanged: "interval-changed",
popupShow: "popup-show"
})

/** user-defined constants **/



/** user-defined types **/

export type CmdError = string
export type DailyGoal = { day: string; goal_ms: number }
export type DailyTotal = { day: string; total_ms: number }
export type IdleDetected = { idleSinceMs: number }
export type Interval = { id: number; start_ms: number; end_ms: number | null }
export type IntervalChanged = Record<string, never>
export type PopupShow = { title: string; message: string }
export type RangeTotal = { total_ms: number; most_recent: Interval | null }
export type TimerState = { state: "Empty" } | { state: "Running"; start_ms: number } | { state: "Paused"; last_duration_ms: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
